name: Build and launch main tests on Pull Requests

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false

    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    # Checkout global JBT settings.xml
    - name: Checkout JBoss Tools Build CI
      uses: actions/checkout@v2
      with:
        repository: jbosstools/jbosstools-build-ci
        path: build-ci

    - name: Setup Java 8
      uses: actions/setup-java@v2.0.0
      with:
        distribution: 'adopt'
        java-version: 8
        java-package: jdk
        architecture: x64
    - name: Set JDK_8_LOCATION
      run: |
        echo "JDK_8_LOCATION=$JAVA_HOME" >> $GITHUB_ENV
    - name: Setup Java 11
      uses: actions/setup-java@v2.0.0
      with:
        distribution: 'adopt'
        java-version: 11
        java-package: jdk
        architecture: x64

    # Try to find and apply jbosstools cache
    - name: Cache local Maven repository for JBoss Tools components
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: jbosstools-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          jbosstools-${{ runner.os }}-maven-

    # Build and compile using Maven
    - name: Build/Compile and run unit tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: mvn clean verify -Ppack200 -P!templates-integration-test,without-templates-integration-test -U -fae --settings build-ci/maven-settings.xml -DskipITests=true -Dmaven.test.error.ignore=true -Dmaven.test.failure.ignore=true --quiet

    # Archive artifacts to be applied in Publish Reports workflow
    - name: Archiving test artifacts
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with: 
        name: ${{ matrix.os }}-test-reports
        path: |
          *tests/*/target/surefire-reports/
          */*tests/*/target/surefire-reports/
          **/*.log/
          **/target/screenshots/**/*.png/
          **/target/MavenLaunchOutputs/**
